launch_file: runWithVoxgraph.launch
time_for_experiment: 200
base_panoptic_yaml_data: "/home/ioannis/catkin_ws/src/panoptic_mapping/panoptic_mapping_ros/config/mapper/flat_groundtruth_with_voxgraph.yaml"
defaults:
  base_name: "runWithVoxgraph_interpolation_"
  name: default
  use_noise: true
  drift_type: severe
  use_sim_time: false
  play_rate: 1
  debug_mode: false
  save_map_path_when_finished: "default_map.panmap"
  shutdown_when_finished: true
  config: "generated"

# no interpolation
experiment1:
  name: light_none
  drift_type: light
  panoptic_yaml_data:
    map_management:
      update_contained_submaps_with_correction: false

experiment2:
  name: moderate_none
  drift_type: moderate
  panoptic_yaml_data:
    map_management:
    map_management:
      update_contained_submaps_with_correction: false

experiment3:
  name: strong_none
  drift_type: strong
  panoptic_yaml_data:
    map_management:
    map_management:
      update_contained_submaps_with_correction: false

experiment4:
  name: severe_none
  drift_type: severe
  panoptic_yaml_data:
    map_management:
    map_management:
      update_contained_submaps_with_correction: false

# linear
experiment5:
  name: light_linear
  drift_type: light
  panoptic_yaml_data:
    map_management:
    map_management:
      update_contained_submaps_with_correction: true

experiment6:
  name: moderate_linear
  drift_type: moderate
  panoptic_yaml_data:
    map_management:
    map_management:
      update_contained_submaps_with_correction: true

experiment7:
  name: strong_linear
  drift_type: strong
  panoptic_yaml_data:
    map_management:
    map_management:
      update_contained_submaps_with_correction: true

experiment8:
  name: severe_linear
  drift_type: severe
  panoptic_yaml_data:
    map_management:
    map_management:
      update_contained_submaps_with_correction: true
