launch_file: runWithVoxgraph.launch
time_for_experiment: 200
base_voxgraph_yaml_data: "/home/ioannis/catkin_ws/src/panoptic_mapping/panoptic_mapping_utils/config/voxgraph/voxgraph_mapper.yaml"
defaults:
  base_name: "runWithVoxgraph_plane_collection"
  name: default
  use_noise: true
  drift_type: strong
  use_sim_time: false
  play_rate: 1
  debug_mode: false
  save_map_path_when_finished: "default_map.panmap"
  shutdown_when_finished: true
  config: "generated"
  voxgraph_config: "/home/ioannis/catkin_ws/src/panoptic_mapping/panoptic_mapping_utils/config/voxgraph/voxgraph_mapper_generated.yaml"

experiment1:
  name: factor_0_1
  drift_type: strong
  voxgraph_yaml_data:
    measurements:
      submap_registration:
        enabled: false
      planes:
        enabled: true
        information_matrix:
          x_x:     100.0
          y_y:     100.0
          z_z:     250.0
          yaw_yaw: 100.0
    tsdf_voxel_size: 0.05

experiment2:
  name: factor_0_2
  drift_type: strong
  voxgraph_yaml_data:
    measurements:
      submap_registration:
        enabled: false
      planes:
        enabled: true
        information_matrix:
          x_x:     200.0
          y_y:     200.0
          z_z:     500.0
          yaw_yaw: 200.0

experiment3:
  name: factor_0_5
  drift_type: strong
  voxgraph_yaml_data:
    measurements:
      submap_registration:
        enabled: false
      planes:
        enabled: true
        information_matrix:
          x_x:     500.0
          y_y:     500.0
          z_z:     1250.0
          yaw_yaw: 500.0

experiment4:
  name: factor_1
  drift_type: strong
  voxgraph_yaml_data:
    measurements:
      submap_registration:
        enabled: false
      planes:
        enabled: true
        information_matrix:
          x_x:     1000.0
          y_y:     1000.0
          z_z:     2500.0
          yaw_yaw: 1000.0

experiment5:
  name: factor_1_5
  drift_type: strong
  voxgraph_yaml_data:
    measurements:
      submap_registration:
        enabled: false
      planes:
        enabled: true
        information_matrix:
          x_x:     1500.0
          y_y:     1500.0
          z_z:     3750.0
          yaw_yaw: 1500.0

experiment6:
  name: factor_2
  drift_type: strong
  voxgraph_yaml_data:
    measurements:
      submap_registration:
        enabled: false
      planes:
        enabled: true
        information_matrix:
          x_x:     2000.0
          y_y:     2000.0
          z_z:     5000.0
          yaw_yaw: 2000.0

experiment7:
  name: factor_5
  drift_type: strong
  voxgraph_yaml_data:
    measurements:
      submap_registration:
        enabled: false
      planes:
        enabled: true
        information_matrix:
          x_x:     5000.0
          y_y:     5000.0
          z_z:     12500.0
          yaw_yaw: 5000.0

experiment8:
  name: factor_10
  drift_type: strong
  voxgraph_yaml_data:
    measurements:
      submap_registration:
        enabled: false
      planes:
        enabled: true
        information_matrix:
          x_x:     10000.0
          y_y:     10000.0
          z_z:     25000.0
          yaw_yaw: 10000.0

experiment9:
  name: factor_20
  drift_type: strong
  voxgraph_yaml_data:
    measurements:
      submap_registration:
        enabled: false
      planes:
        enabled: true
        information_matrix:
          x_x:     20000.0
          y_y:     20000.0
          z_z:     50000.0
          yaw_yaw: 20000.0

experiment10:
  name: factor_100
  drift_type: strong
  voxgraph_yaml_data:
    measurements:
      submap_registration:
        enabled: false
      planes:
        enabled: true
        information_matrix:
          x_x:     100000.0
          y_y:     100000.0
          z_z:     250000.0
          yaw_yaw: 100000.0
