# this has something wrong
verbose: true
world_frame: "world"
color_mode: "normals"

method: "projective"
sensor_horizontal_resolution: 640
sensor_vertical_resolution: 480
sensor_horizontal_field_of_view_degrees: 90
sensor_vertical_field_of_view_degrees: 73.73979529
integrator_threads: 1

tsdf_voxel_size: 0.05
truncation_distance: 0.5
max_weight: 1000
pointcloud_queue_size: 100
max_ray_length_m: 5.0
min_ray_length_m: 0.1
max_consecutive_ray_collisions: 1
use_const_weight: true
use_weight_dropoff: false

icp_refine_roll_pitch: false
tsdf_integrator:
  type: projective # projective, class_projective, single_tsdf
  verbosity: 1

mesh_min_weight: 2
# publish_pointclouds_on_update: true
# slice_level: 1.0
# publish_slices: true
update_mesh_every_n_sec: 1.0

pointcloud_deintegration_queue_length: 30
publish_submap_every_n_sec: 6.0
