launch_file: runWithVoxgraph_small.launch
time_for_experiment: 200
base_panoptic_yaml_data: "/home/ioannis/catkin_ws/src/panoptic_mapping/panoptic_mapping_ros/config/mapper/flat_groundtruth_with_voxgraph.yaml"
base_voxgraph_yaml_data: "/home/ioannis/catkin_ws/src/panoptic_mapping/panoptic_mapping_utils/config/voxgraph/voxgraph_mapper.yaml"
defaults:
  base_path: "/home/ioannis/datasets/flat_dataset/run1"
  base_name: "runWithVoxgraph_"
  name: default
  use_noise: true
  drift_type: severe
  use_sim_time: false
  play_rate: 1
  debug_mode: false
  save_map_path_when_finished: "default_map.panmap"
  shutdown_when_finished: true
  config: "generated"
  voxgraph_config: "/home/ioannis/catkin_ws/src/panoptic_mapping/panoptic_mapping_utils/config/voxgraph/voxgraph_mapper_generated.yaml"

# run 1 no use of our algo
experiment1:
  name: moderate_none_run1
  drift_type: none
  ground_truth_pointcloud_file: "/home/ioannis/datasets/flat_dataset/flat_1_gt_10000.ply"
  panoptic_yaml_data:
    map_management:
      merge_deactivated_submaps_if_possible: true
      avoid_merging_deactivated_background_submaps: false
      send_deactivated_submaps_to_voxgraph: false
      use_submap_stitching: false
      optimize_poses_online: false
    id_tracker:
      type: single_tsdf # ground_truth, projective, detectron, single_tsdf, dual_mode
      verbosity: 1
    tsdf_integrator:
      type: single_tsdf # projective, class_projective, multi_class_projective, single_tsdf
      verbosity: 1
      # single tsdf
      use_segmentation: false
      # multi_class
      id_classes_set_1: [0,1,2,3,4,5]
      # Projective
      use_weight_dropoff: true
      max_weight: 10000
      interpolation_method: adaptive  # nearest, bilinear, adaptive
      foreign_rays_clear: true
      integration_threads: 8
      allocate_neighboring_blocks: false
      # Class Projective
      use_binary_classification: true
      use_instance_classification: false
      update_only_tracked_submaps: true
  voxgraph_yaml_data:
    measurements:
      submap_registration:
        sampling_ratio: 1.0
        enabled: true
      odometry:
        enabled: true
      planes:
        enabled: false
# run 2 no use of our algo
experiment2:
  name: moderate_none_run2
  drift_type: moderate
  base_path: "/home/ioannis/datasets/flat_dataset/run2"
  ground_truth_pointcloud_file: "/home/ioannis/datasets/flat_dataset/flat_2_gt_10000.ply"
  panoptic_yaml_data:
    map_management:
      merge_deactivated_submaps_if_possible: true
      avoid_merging_deactivated_background_submaps: false
      send_deactivated_submaps_to_voxgraph: false
      use_submap_stitching: false
      optimize_poses_online: false
    id_tracker:
      type: single_tsdf # ground_truth, projective, detectron, single_tsdf, dual_mode
      verbosity: 1
    tsdf_integrator:
      type: single_tsdf # projective, class_projective, multi_class_projective, single_tsdf
      verbosity: 1
      # single tsdf
      use_segmentation: false
      # multi_class
      id_classes_set_1: [0,1,2,3,4,5]
      # Projective
      use_weight_dropoff: true
      max_weight: 10000
      interpolation_method: adaptive  # nearest, bilinear, adaptive
      foreign_rays_clear: true
      integration_threads: 8
      allocate_neighboring_blocks: false
      # Class Projective
      use_binary_classification: true
      use_instance_classification: false
      update_only_tracked_submaps: true
    data_writer:
      verbosity: 1
      output_directory: "/home/ioannis/datasets/temporal_voxgraph_map_metric/experiment1/"
      file_name: ""
      store_map_every_n_frames: 10  # Use 0 to ignore
  voxgraph_yaml_data:
    measurements:
      submap_registration:
        sampling_ratio: 1.0
        enabled: true
      odometry:
        enabled: true
      planes:
        enabled: false

# change detection no use of our algo (loads map)
experiment3:
  name: moderate_none_run2_change
  drift_type: moderate
  base_path: "/home/ioannis/datasets/flat_dataset/run2"
  load_map: true
  load_file: "/home/ioannis/datasets/temporal_voxgraph_map_metric/experiment0/runWithVoxgraph_moderate_none_run1.panmap"
  ground_truth_pointcloud_file: "/home/ioannis/datasets/flat_dataset/flat_2_gt_10000.ply"
  panoptic_yaml_data:
    visualization:
      submaps:
        color_mode: change
    map_management:
      merge_deactivated_submaps_if_possible: true
      avoid_merging_deactivated_background_submaps: false
      send_deactivated_submaps_to_voxgraph: false
      use_submap_stitching: false
      optimize_poses_online: false
    id_tracker:
      type: single_tsdf # ground_truth, projective, detectron, single_tsdf, dual_mode
      verbosity: 1
    tsdf_integrator:
      type: single_tsdf # projective, class_projective, multi_class_projective, single_tsdf
      verbosity: 1
      # single tsdf
      use_segmentation: false
      # multi_class
      id_classes_set_1: [0,1,2]
      # Projective
      use_weight_dropoff: true
      max_weight: 10000
      interpolation_method: adaptive  # nearest, bilinear, adaptive
      foreign_rays_clear: true
      integration_threads: 8
      allocate_neighboring_blocks: false
      # Class Projective
      use_binary_classification: true
      use_instance_classification: false
      update_only_tracked_submaps: true
      optimize_last_background_separately: true
    data_writer:
      verbosity: 1
      output_directory: "/home/ioannis/datasets/temporal_voxgraph_map_metric/experiment2/"
      file_name: ""
      store_map_every_n_frames: 10  # Use 0 to ignore
  voxgraph_yaml_data:
    measurements:
      submap_registration:
        sampling_ratio: 1.0
        enabled: true
      odometry:
        enabled: true
      planes:
        enabled: false
# run 1 use of our algo
experiment4:
  name: moderate_proposed_run1
  drift_type: none
  ground_truth_pointcloud_file: "/home/ioannis/datasets/flat_dataset/flat_1_gt_10000.ply"
  panoptic_yaml_data:
    id_tracker:
      type: dual_mode # ground_truth, projective, detectron, single_tsdf, dual_mode
      verbosity: 1
    tsdf_integrator:
      type: multi_class_projective # projective, class_projective, multi_class_projective, single_tsdf
      verbosity: 1
    map_management:
      send_deactivated_submaps_to_voxgraph: false
      optimize_last_background_separately: true
  voxgraph_yaml_data:
    measurements:
      submap_registration:
        sampling_ratio: 1.0
        enabled: true
      odometry:
        enabled: true
      planes:
        enabled: false
# run 2 use of our algo
experiment5:
  name: moderate_proposed_run2
  drift_type: moderate
  base_path: "/home/ioannis/datasets/flat_dataset/run2"
  ground_truth_pointcloud_file: "/home/ioannis/datasets/flat_dataset/flat_2_gt_10000.ply"
  panoptic_yaml_data:
    map_management:
      send_deactivated_submaps_to_voxgraph: true
      optimize_last_background_separately: true
    data_writer:
      verbosity: 1
      output_directory: "/home/ioannis/datasets/temporal_voxgraph_map_metric/experiment4/"
      file_name: ""
      store_map_every_n_frames: 10  # Use 0 to ignore
  voxgraph_yaml_data:
    measurements:
      submap_registration:
        sampling_ratio: 1.0
        enabled: true
      odometry:
        enabled: true
      planes:
        enabled: false
# change detection use of our algo (loads map)
experiment6:
  name: moderate_proposed_run2_change
  drift_type: moderate
  base_path: "/home/ioannis/datasets/flat_dataset/run2"
  load_map: true
  load_file: "/home/ioannis/datasets/temporal_voxgraph_map_metric/experiment3/runWithVoxgraph_moderate_proposed_run1.panmap"
  ground_truth_pointcloud_file: "/home/ioannis/datasets/flat_dataset/flat_2_gt_10000.ply"
  panoptic_yaml_data:
    visualization:
      submaps:
        color_mode: change
    map_management:
      send_deactivated_submaps_to_voxgraph: true
    data_writer:
      verbosity: 1
      output_directory: "/home/ioannis/datasets/temporal_voxgraph_map_metric/experiment5/"
      store_map_every_n_frames: 10  # Use 0 to ignore
  voxgraph_yaml_data:
    measurements:
      submap_registration:
        sampling_ratio: 1.0
        enabled: true
      odometry:
        enabled: true
      planes:
        enabled: false



